- name: mkdir dhparams
  file: path=/etc/postfix/ssl/dhparams state=directory owner=root group=root mode=0700

- name: mkdir selfsigned
  file: path=/etc/postfix/ssl/selfsigned state=directory owner=root group=root mode=0700

- name: copy dhparams
  copy:
    src: "roles/ssl/files/{{ item.src }}"
    dest: "/etc/postfix/ssl/dhparams/{{ item.dest }}"
    backup: no
    owner: root
    group: root
    mode: 0644
  loop:
    - { src: "dh2048.pem", dest: . }
    - { src: "dh512.pem", dest: . }

- name: copy selfsigned
  copy:
    src: "roles/ssl/files/{{ item.src }}"
    dest: "/etc/postfix/ssl/selfsigned/{{ item.dest }}"
    backup: no
    owner: root
    group: root
    mode: 0644
  loop:
    - { src: "privkey.pem", dest: . }
    - { src: "cert.pem", dest: . }

