- name: install fail2ban
  yum: name=fail2ban state=present

- name: start fail2ban
  systemd: name=fail2ban enabled=yes state=started

    - { src: roles/fail2ban/files/filter.d/h2o-xmlrpc.conf, dest: . }

- name: copy fail2ban jail.d
  copy:
    src: "{{ item.src }}"
    dest: "/etc/fail2ban/jail.d/{{ item.dest }}"
    owner: root
    group: root
  loop:
    - { src: roles/fail2ban/files/jail.d/sshd.conf, dest: . }
    - { src: roles/fail2ban/files/jail.d/postfix.conf, dest: . }

- name: copy fail2ban jail.conf
  copy:
    src: "{{ item.src }}"
    dest: "/etc/fail2ban/{{ item.dest }}"
    owner: root
    group: root
  loop:
    - { src: roles/fail2ban/files/jail.conf, dest: . }
  notify: restart fail2ban

