- name: install fail2ban
  yum: name=fail2ban state=present

- name: start fail2ban
  systemd: name=fail2ban enabled=yes state=started

  #- name: copy jail.local
  #  copy:
  #    src: "roles/fail2ban/files/{{ item.src }}"
  #    dest: "/etc/fail2ban/jail.d/"
  #    backup: no
  #    owner: root
  #    group: root
  #    mode: 0644
  #  loop:
  #    - { src: jail.local }
  #  notify: restart fail2ban
