- name: copy postfixadmin
  copy:
    src: "roles/postfixadmin/files/{{ item.src }}"
    dest: "/var/www/postfixadmin/{{ item.dest }}"
    backup: no
    owner: nobody
    group: nobody
    mode: 0700
  loop:
    - { src: "postfixadmin", dest: . }

- name: copy sh
  copy:
    src: "roles/postfixadmin/files/{{ item.src }}"
    dest: "/var/vmail/bin/{{ item.dest }}"
    backup: no
    owner: vmail
    group: vmail
    mode: 0700
  loop:
    - { src: "postfixadmin-mailbox-postcreation.sh", dest: . }
    - { src: "postfixadmin-mailbox-postdeletion.sh", dest: . }
    - { src: "postfixadmin-domain-postdeletion.sh", dest: . }
